import axios from 'axios';
import type { NextPage, GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { IPost } from 'backend-types';

type Awaited<T> = T extends PromiseLike<infer U> ? U : T;

const Home: NextPage<Awaited<ReturnType<typeof getServerSideProps>>['props']> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Hello there!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {posts.map(({ title, slug }) => (
          <div key={slug}>{title}</div>
        ))}
      </div>
    </>
  );
};

export default Home;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { data: posts } = await axios.get<IPost[]>('http://localhost:1337/posts?_sort=publish_date:DESC');
  return { props: { posts } };
}
